### ISSUE TITLE
Depth Chart Issues

### ISSUE THREAD

**Issue by ColinB19** [nflverse/nflverse-rosters#86]
I noticed that the depth charts data seems to indicate that Desmond Ridder started for the Falcons in week 16 vs. the Colts. However, the Falcons [official website](https://www.atlantafalcons.com/news/falcons-release-depth-chart-heading-into-week-16-of-the-2023-regular-season) has Taylor Heinicke starting. Taylor Heinicke also received all the passing stats for that week. Not sure if this issue shows up anywhere else yet. 
![image](https://github.com/nflverse/nflverse-rosters/assets/59992468/8fcea5f4-6301-4bde-9ec7-063b31876914)

**Comment by john-b-edwards** [comment]
Hi Colin, thanks for letting us know. As is the case when people flag issues with the depth charts, I checked our data source in the NFL Data Exchange to verify that what we're providing aligns with what's in up in the API. I was able to confirm that the Data Exchange has Ridder listed as the #1 QB on the depth chart for week 16.

[This is obviously inconsistent with the Falcons' actual depth chart from ahead of that week](https://www.atlantafalcons.com/news/falcons-release-depth-chart-heading-into-week-16-of-the-2023-regular-season)--given that Ridder was benched that week, I suspect that the depth charts here reflect the Falcons depth chart prior to the decision being made to elevate Heinicke as the starter.

Because ensuring historical and present depth charts are 100% correct is an exhaustive and full-time endeavor, this function simply seeks to present the depth charts from the data exchange as is, [and as in the past](https://github.com/nflverse/nflverse-data/issues/21), I am considering manual depth chart editing to be beyond the scope of this work.
